#Twitter US Airline Sentiment

A sentiment analysis job about the problems of each major U.S. airline. Twitter data was scraped from February of 2015 and contributors were asked to first classify positive, negative, and neutral tweets, followed by categorizing negative reasons.
it contains whether the sentiment of the tweets in this set was positive, neutral, or negative for six US airlines

In [ ]:
# import all libraries
import pandas as pd
import pandas as pd
import re
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#read a csv file
df = pd.read_csv('/content/drive/MyDrive/datascience/project /main NLP/Tweets.csv')

In [ ]:
#First 30 rows
df.head(30)

tweet_id airline_sentiment  airline_sentiment_confidence  \
0   570306133677760513           neutral                        1.0000   
1   570301130888122368          positive                        0.3486   
2   570301083672813571           neutral                        0.6837   
3   570301031407624196          negative                        1.0000   
4   570300817074462722          negative                        1.0000   
5   570300767074181121          negative                        1.0000   
6   570300616901320704          positive                        0.6745   
7   570300248553349120           neutral                        0.6340   
8   570299953286942721          positive                        0.6559   
9   570295459631263746          positive                        1.0000   
10  570294189143031808           neutral                        0.6769   
11  570289724453216256          positive                        1.0000   
12  570289584061480960          positive                        1.0000   
13  570287408438120448          positive                        0.6451   
14  570285904809598977          positive                        1.0000   
15  570282469121007616          negative                        0.6842   
16  570277724385734656          positive                        1.0000   
17  570276917301137409          negative                        1.0000   
18  570270684619923457          positive                        1.0000   
19  570267956648792064          positive                        1.0000   
20  570265883513384960          negative                        0.6705   
21  570264145116819457          positive                        1.0000   
22  570259420287868928          positive                        1.0000   
23  570258822297579520           neutral                        1.0000   
24  570256553502068736          negative                        1.0000   
25  570249102404923392          negative                        1.0000   
26  570239632807370753          negative                        1.0000   
27  570217831557677057           neutral                        0.6854   
28  570207886493782019          negative                        1.0000   
29  570124596180955136           neutral                        0.6150   

             negativereason  negativereason_confidence         airline  \
0                Bad Flight                     0.0000  Virgin America   
1                Bad Flight                     0.0000  Virgin America   
2                Bad Flight                     0.7033  Virgin America   
3                Bad Flight                     0.7033  Virgin America   
4                Can't Tell                     1.0000  Virgin America   
5                Can't Tell                     0.6842  Virgin America   
6               Late Flight                     0.0000  Virgin America   
7               Late Flight                     0.0000  Virgin America   
8               Late Flight                     0.0000  Virgin America   
9               Late Flight                     0.0000  Virgin America   
10              Late Flight                     0.0000  Virgin America   
11              Late Flight                     0.3684  Virgin America   
12              Late Flight                     0.3684  Virgin America   
13              Late Flight                     0.3684  Virgin America   
14              Late Flight                     0.3684  Virgin America   
15              Late Flight                     0.3684  Virgin America   
16               Bad Flight                     1.0000  Virgin America   
17               Bad Flight                     1.0000  Virgin America   
18               Can't Tell                     0.3614  Virgin America   
19               Can't Tell                     0.3614  Virgin America   
20               Can't Tell                     0.3614  Virgin America   
21   Customer Service Issue                     0.3557  Virgin America   
22   Customer Ser

In [ ]:
#last 20 rows
df.tail(20)

tweet_id airline_sentiment  airline_sentiment_confidence  \
14620  569590965880532993          negative                        1.0000   
14621  569590892085915649          negative                        1.0000   
14622  569590191758962688          negative                        1.0000   
14623  569590013278756865          positive                        0.6274   
14624  569589959088173056          negative                        1.0000   
14625  569589643487928321          positive                        1.0000   
14626  569589460226183168          negative                        1.0000   
14627  569588816438169600          negative                        1.0000   
14628  569588651925098496          positive                        1.0000   
14629  569588591602458624          negative                        1.0000   
14630  569588473050611712          positive                        1.0000   
14631  569588464896876545          negative                        1.0000   
14632  569587813856841728           neutral                        0.6760   
14633  569587705937600512          negative                        1.0000   
14634  569587691626622976          negative                        0.6684   
14635  569587686496825344          positive                        0.3487   
14636  569587371693355008          negative                        1.0000   
14637  569587242672398336           neutral                        1.0000   
14638  569587188687634433          negative                        1.0000   
14639  569587140490866689           neutral                        0.6771   

               negativereason  negativereason_confidence   airline  \
14620  Customer Service Issue                     1.0000  American   
14621  Customer Service Issue                     1.0000  American   
14622             Late Flight                     0.3358  American   
14623              Can't Tell                     0.0000  American   
14624              Can't Tell                     1.0000  American   
14625             Late Flight                     1.0000  American   
14626             Late Flight                     1.0000  American   
14627        Cancelled Flight                     1.0000  American   
14628  Customer Service Issue                     1.0000  American   
14629  Customer Service Issue                     1.0000  American   
14630              Bad Flight                     1.0000  American   
14631              Bad Flight                     1.0000  American   
14632        Cancelled Flight                     0.0000  American   
14633        Cancelled Flight                     1.0000  American   
14634             Late Flight                     0.6684  American   
14635  Customer Service Issue                     0.0000  American   
14636  Customer Service Issue                     1.0000  American   
14637  Customer Service Issue                     0.6659  American   
14638  Customer Service Issue                     0.6659  American   
14639  Customer Service Issue                     0.0000  American   

      airline_sentiment_gold             name  \
14620               negative         KCBobolz   
14621               negative      andyellwood   
14622               negative    Jill_Lynnette   
14623               negative   Flora_Lola_NYC   
14624               negative         yourlama   
14625               negative   DrCaseyJRudkin   
14626               negative       cataattack   
14627               negative   KristinaMeyer7   
14628               negative         jlhalldc   
14629               negative      jontgreen89   
14630               negative   Laurelinesblog   
14631               negative         MDDavis7   
14632               negative       Chad_SMFYM   
14633               negative  RussellsWriting   
14634               negative    GolfWithWoody   
14635               negative  KristenReenders   
14636               negative         itsropes   
14637               negative         sanyabun 

In [ ]:
#dataset shape
df.shape

(14640, 15)

In [ ]:
#display dataframe information like colimn details,datatype,memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   tweet_id                      14640 non-null  int64  
 1   airline_sentiment             14640 non-null  object 
 2   airline_sentiment_confidence  14640 non-null  float64
 3   negativereason                9178 non-null   object 
 4   negativereason_confidence     10522 non-null  float64
 5   airline                       14640 non-null  object 
 6   airline_sentiment_gold        40 non-null     object 
 7   name                          14640 non-null  object 
 8   negativereason_gold           32 non-null     object 
 9   retweet_count                 14640 non-null  int64  
 10  text                          14640 non-null  object 
 11  tweet_coord                   1019 non-null   object 
 12  tweet_created                 14640 non-null  object 
 13  t

In [ ]:
#check the null value
df.isnull().sum()

tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5462
negativereason_confidence        4118
airline                             0
airline_sentiment_gold          14600
name                                0
negativereason_gold             14608
retweet_count                       0
text                                0
tweet_coord                     13621
tweet_created                       0
tweet_location                   4733
user_timezone                    4820
dtype: int64

In [ ]:
#null value percentage
percentage = (df.isna().sum()/df.shape[0])*100
percent = pd.DataFrame(percentage)
percent


0
tweet_id                       0.000000
airline_sentiment              0.000000
airline_sentiment_confidence   0.000000
negativereason                37.308743
negativereason_confidence     28.128415
airline                        0.000000
airline_sentiment_gold        99.726776
name                           0.000000
negativereason_gold           99.781421
retweet_count                  0.000000
text                           0.000000
tweet_coord                   93.039617
tweet_created                  0.000000
tweet_location                32.329235
user_timezone                 32.923497

In [ ]:
#removung null value using bfill and ffill
df.fillna(method='bfill',inplace=True)

<ipython-input-61-c117f11b49be>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill',inplace=True)


In [ ]:

df.fillna(method='ffill',inplace=True)

<ipython-input-62-22209d75fb66>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',inplace=True)


In [ ]:
df.isnull().sum()

tweet_id                        0
airline_sentiment               0
airline_sentiment_confidence    0
negativereason                  0
negativereason_confidence       0
airline                         0
airline_sentiment_gold          0
name                            0
negativereason_gold             0
retweet_count                   0
text                            0
tweet_coord                     0
tweet_created                   0
tweet_location                  0
user_timezone                   0
dtype: int64

In [ ]:
#column names
df.columns

Index(['tweet_id', 'airline_sentiment', 'airline_sentiment_confidence',
       'negativereason', 'negativereason_confidence', 'airline',
       'airline_sentiment_gold', 'name', 'negativereason_gold',
       'retweet_count', 'text', 'tweet_coord', 'tweet_created',
       'tweet_location', 'user_timezone'],
      dtype='object')

In [ ]:
#duplicate rows
dpl_rows = df.duplicated()
print(dpl_rows)

0        False
1        False
2        False
3        False
4        False
         ...  
14635    False
14636    False
14637    False
14638    False
14639    False
Length: 14640, dtype: bool


In [ ]:
#Extracting features and labels
features = df.iloc[:,10].values
labels = df.iloc[:,1].values

In [ ]:
processed_features = []
for sentence in range(0, len(features)):
  # Remove all the special characters
  processed_feature = re.sub(r'\W', ' ', str(features[sentence]))

  # remove all single characters
  processed_feature= re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_feature)

  #remove single characters from the start
  processed_feature = re.sub(r'\^[a-zA-Z]\s+', ' ', processed_feature)

  #substituting multiple spaces with single space
  processed_feature = re.sub(r'\s+', ' ', processed_feature, flags=re.I)

  #removing prefixed 'b'
  processed_feature = re.sub(r'^b\s+', '', processed_feature)

  #converting to lowercase
  processed_feature = processed_feature.lower()

  processed_features.append(processed_feature)

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
#word_tokenize : this step ensures that very short words are removed from the text.


from nltk.tokenize import word_tokenize

# Assuming 'features' is your existing numpy array
features_series = pd.Series(processed_features) # Convert to pandas Series

processed_features= features_series.apply(lambda x:' '.join([w for w in word_tokenize(x) if len(w)>=3]))

In [ ]:
#stemming:this step standardizes the text by reducing word to their base forms.

from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer('english')


processed_features = processed_features.apply(lambda x:[stemmer.stem(i.lower()) for i in word_tokenize(x)]).apply(lambda x:' '.join(x))

In [ ]:
#stopword removal and TF-IDF vectorization

from nltk.corpus import stopwords
nltk.download('stopwords')    # stopword package is downloaded
from sklearn.feature_extraction.text import TfidfVectorizer
#TfidfVectorizer :converts the yext data into a numerical matrix based on Term Frequency-Inverse Document Frequency(TF-IDF)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
vectorizer = TfidfVectorizer(max_features=2500,min_df=7,max_df=0.8,stop_words=stopwords.words('english'))
processed_feature = vectorizer.fit_transform(processed_features).toarray()

In [ ]:
#dividing data into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(processed_feature, labels, test_size=0.2, random_state=0)

LogisticRegression MODEL

In [ ]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(x_train, y_train)

LogisticRegression()

In [ ]:
lr_y_pred = lr_model.predict(x_test)


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,lr_y_pred))
print(accuracy_score(y_test,lr_y_pred))

[[1729  112   29]
 [ 259  316   39]
 [ 116   58  270]]
0.7906420765027322


accuracy score :0.79

In [ ]:
x_test_pred = lr_model.predict(x_test)
test_accuracy = accuracy_score(x_test_pred,y_test)
test_accuracy

0.7906420765027322

In [ ]:
#print classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,lr_y_pred))

              precision    recall  f1-score   support

    negative       0.82      0.92      0.87      1870
     neutral       0.65      0.51      0.57       614
    positive       0.80      0.61      0.69       444

    accuracy                           0.79      2928
   macro avg       0.76      0.68      0.71      2928
weighted avg       0.78      0.79      0.78      2928



prediction using LogisticRegression model

In [ ]:
text = 'Cancelled Flight'

In [ ]:
#prediction of the text
input_data = [text] # Use text directly, it is already a string
input_data = vectorizer.transform(input_data).toarray()
prediction = lr_model.predict(input_data)
print(prediction)


['negative']


RandomForest MODEL

In [ ]:
from sklearn.ensemble import RandomForestClassifier
random_model = RandomForestClassifier(n_estimators=200,random_state=0)
random_model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=0)

In [ ]:
random_y_pred = random_model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,random_y_pred))
print(accuracy_score(y_test,random_y_pred))

[[1723  114   33]
 [ 306  267   41]
 [ 149   60  235]]
0.7599043715846995


accuracy score : 0.759

In [ ]:
#print classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,random_y_pred))

              precision    recall  f1-score   support

    negative       0.79      0.92      0.85      1870
     neutral       0.61      0.43      0.51       614
    positive       0.76      0.53      0.62       444

    accuracy                           0.76      2928
   macro avg       0.72      0.63      0.66      2928
weighted avg       0.75      0.76      0.74      2928



predition using RandomForest model

In [ ]:
text1='Flight Booking Problems'

In [ ]:
input_data = [text] # Use text directly, it is already a string
input_data = vectorizer.transform(input_data).toarray()
prediction = random_model.predict(input_data)
print(prediction)

['neutral']
